import Head from 'next/head'
import Header from './header';
import Link from 'next/link'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Trip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header/>
        <h1>
          Welcome
        </h1>

        <br/>
        <Link href="/problems">
          <a>Problems</a>
        </Link>

        
      </main>
    </div>
  )
}
